services:
  db.menu:
    image: mysql:9
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass123
      MYSQL_DATABASE: menu
    ports:
      - '3306:3306'
    volumes:
      - mysql.menu:/var/lib/mysql

volumes:
  mysql.menu:
